# exclude library folder from checks, except prometheus library itself
exclude: ^((?!lib/charms/prometheus_k8s)lib).*$
repos:
  - repo: https://github.com/PyCQA/autoflake
    rev: v1.7.6
    hooks:
      - id: autoflake
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: https://github.com/asottile/blacken-docs
    rev: v1.12.1
    hooks:
      - id: blacken-docs
        additional_dependencies: [black]
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)

  # official flake8 doesn't support pyproject.toml configuration.
  - repo: https://github.com/csachs/pyproject-flake8
    rev: v5.0.4
    hooks:
      - id: pyproject-flake8
        name: pyproject-flake8

  - repo: https://github.com/Lucas-C/pre-commit-hooks-nodejs
    rev: v1.1.2
    hooks:
      - id: markdown-toc
        name: Table of Contents
